version: '3'

services:
  jekyll:
    build: 
      context: .
      dockerfile: Dockerfile
    image: clab-jekyll:1.0.0
    command: jekyll serve --watch --force_polling --verbose
    volumes:
      - ../site:/srv/jekyll
    ports:
      - "4000:4000"
    restart: always
